/**
 * SKU Generation Utilities
 *
 * Generates stable, readable SKUs for hamper variants.
 * Format: {HAMPER_PREFIX}-{LISTING_SUFFIX}-{VARIANT_CODE}
 * Example: "PTSH-4437-BRN" for "Physical T-Shirt" listing 4437179096, variant "Brown"
 */

/**
 * Sanitize a string for SKU use - uppercase, alphanumeric only
 */
function sanitize(str: string): string {
  return str
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .trim();
}

/**
 * Create an abbreviation from a name
 * Takes first letter of each word, or consonant-based abbreviation for single words
 */
function abbreviate(name: string, maxLen: number): string {
  const words = name.split(/\s+/).filter(Boolean);

  if (words.length >= 2) {
    // Multi-word: take first letter of each word
    return sanitize(words.map(w => w[0]).join('')).slice(0, maxLen);
  }

  // Single word: use first char + consonants to create more unique abbreviation
  const sanitized = sanitize(name);
  if (sanitized.length <= maxLen) {
    return sanitized;
  }

  // Take first char + next consonants (skip vowels after first char for uniqueness)
  const firstChar = sanitized[0];
  const rest = sanitized.slice(1).replace(/[AEIOU]/g, '');
  const abbrev = firstChar + rest;

  return abbrev.slice(0, maxLen);
}

/**
 * Generate a SKU for a hamper variant
 *
 * @param hamperName - The hamper/listing name (e.g., "Physical T-Shirt")
 * @param variantName - The variant name (e.g., "Brown")
 * @param listingId - The Etsy listing ID (e.g., "4437179096")
 * @returns A generated SKU like "PTSH-4437-BRN"
 */
export function generateVariantSku(
  hamperName: string,
  variantName: string,
  listingId: string
): string {
  // Hamper prefix: 3-4 chars from name
  const hamperPrefix = abbreviate(hamperName, 4) || 'ITEM';

  // Listing suffix: last 4 digits of listing ID for uniqueness
  const listingSuffix = listingId.slice(-4);

  // Variant code: 3 chars from variant name
  const variantCode = abbreviate(variantName, 3) || 'VAR';

  return `${hamperPrefix}-${listingSuffix}-${variantCode}`;
}

/**
 * Generate a SKU for a non-variant hamper
 *
 * @param hamperName - The hamper/listing name
 * @param listingId - The Etsy listing ID
 * @returns A generated SKU like "PTSH-4437"
 */
export function generateHamperSku(
  hamperName: string,
  listingId: string
): string {
  const hamperPrefix = abbreviate(hamperName, 4) || 'ITEM';
  const listingSuffix = listingId.slice(-4);

  return `${hamperPrefix}-${listingSuffix}`;
}

/**
 * Check if a SKU looks auto-generated (matches our pattern)
 */
export function isAutoGeneratedSku(sku: string): boolean {
  // Matches patterns like "XXXX-1234-XXX" or "XXXX-1234"
  return /^[A-Z]{2,4}-\d{4}(-[A-Z]{2,4})?$/.test(sku);
}
